<?php

namespace AppBundle\Repository;

/**
 * UserAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
